// 2-InitialState/vue/src/grid.vue
<template>
  <div v-if="this.gameGrid">
    <Cell v-for="(cell, index) in this.gameGrid" :key="index" :isLive="cell.live"/>
  </div>
</template>

<script>
import Cell from "./cell.vue";
export default {
  name: "Grid",
  components: { Cell },
  props: ["gameGrid"]
};
</script>

<style scoped>
</style>

// 2-InitialState/react/src/grid.js
import React from "react";
import Cell from "./cell";

// eslint-disable-next-line react/prop-types
const Grid = ({ gameGrid }) => {
  return (
    <div className="grid">
      {gameGrid.map((cell, index) => (
        <Cell key={index} cell={cell} />
      ))}
    </div>
  );
};

export default Grid;
