// 5-UI/vue/src/App.vue
<template>
  <div id="app">
    <Grid :gameGrid="this.grid" :key="restartKey"/>
    <Options
      @restartClicked="handleRestartClicked"
      @typeChanged="handleTypeChanged"
      pattern="random"
    />
  </div>
</template>
<script>
import GameEngine from "./engine/gameengine";
import Grid from "./grid.vue";
import Options from "./options.vue";

export default {
  name: "app",
  components: { Grid, Options },
  created() {
    if (this.grid == null) {
      this.grid = this.populateGrid("blinker");
    }
    this.timer = setInterval(() => {
      this.grid = this.grid.map(cell =>
        GameEngine.determineNewState(cell, this.grid)
      );
    }, 1000);
  },
  beforeDestroy() {
    clearInterval(this.timer);
  },
  data() {
    return {
      grid: null,
      restartKey: 0
    };
  },
  methods: {
    handleRestartClicked() {
      this.grid = this.populateGrid(pattern);
      this.restartKey++;
    },
    handleTypeChanged(pattern) {
      this.grid = this.populateGrid(pattern);
      this.restartKey++;
    },
    populateGrid(pattern) {
      switch (pattern) {
        case "blinker":
          return GameEngine.setupBlinker();
        case "toad":
          return GameEngine.setupToad();
        case "beacon":
          return GameEngine.setupBeacon();
        case "pulsar":
          return GameEngine.setupPulsar();
        case "acorn":
          return GameEngine.setupAcorn();
        case "diehard":
          return GameEngine.setupDiehard();
        default:
          return GameEngine.setupRandom();
      }
    }
  }
};
</script>
<style>
#app,
.app {
  font-family: "Avenir", Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  display: grid;
  grid-template-columns: 1fr 200px;
  text-align: center;
}
</style>

// 5-UI/react/src/App.js
import React from "react";
import "./App.css";
import GameEngine from "./engine/gameengine";
import Grid from "./grid";
import Options from "./options";

function App() {
  const setupGrid = pattern => {
    switch (pattern) {
      case "blinker":
        return GameEngine.setupBlinker();
      case "beacon":
        return GameEngine.setupBeacon();
      case "toad":
        return GameEngine.setupToad();
      case "pulsar":
        return GameEngine.setupPulsar();
      case "acorn":
        return GameEngine.setupAcorn();
      case "diehard":
        return GameEngine.setupDiehard();
      default:
        return GameEngine.setupRandom();
    }
  };

  let [pattern, setPattern] = React.useState("random");
  let [grid, setGrid] = React.useState(setupGrid(pattern));
  let [restartKey, setRestartKey] = React.useState(0);

  React.useEffect(() => {
    const timerId = setTimeout(() => {
      const newGrid = grid.map(cell =>
        GameEngine.determineNewState(cell, grid)
      );
      setGrid(newGrid);
    }, 1000);
    return () => clearTimeout(timerId);
  });

  const handleTypeChanged = changeEvent => {
    pattern = changeEvent.target.value;
    setPattern(pattern);
    restartGame();
  };

  const handleRestartClicked = () => {
    event.preventDefault();
    restartGame();
  };

  const restartGame = () => {
    setGrid(setupGrid(pattern));
    setRestartKey(restartKey + 1);
  };

  return (
    <div className="App">
      <Grid key={restartKey} gameGrid={grid} />
      <Options
        pattern={pattern}
        typeChanged={handleTypeChanged}
        restartClick={handleRestartClicked}
      />
    </div>
  );
}

export default App;
